version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - cadenafrio-net
    environment:
      - CASSANDRA_CLUSTER_NAME=SupervisionCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  app:
    build:
      context: .
    container_name: supervision-app
    ports:
      - "8085:8085"
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      - SPRING_CASSANDRA_CONTACT_POINTS=cassandra
      - SPRING_CASSANDRA_PORT=9042
      - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
      - WAIT_FOR_CASSANDRA=true
    networks:
      - cadenafrio-net
    restart: on-failure

networks:
  cadenafrio-net:
    driver: bridge
